# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/calculator.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='protos/calculator.proto',
  package='sample',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x17protos/calculator.proto\x12\x06sample\"\x8e\x01\n\nC2SRequest\x12\x0b\n\x03lhs\x18\x01 \x01(\x05\x12\x0b\n\x03rhs\x18\x02 \x01(\x05\x12(\n\x02op\x18\x03 \x01(\x0e\x32\x1c.sample.C2SRequest.Operation\"<\n\tOperation\x12\x07\n\x03\x41\x64\x64\x10\x00\x12\x0c\n\x08Subtract\x10\x01\x12\x0c\n\x08Multiply\x10\x02\x12\n\n\x06\x44ivide\x10\x03\"+\n\x08S2CReply\x12\x0e\n\x06result\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t2B\n\x0b\x43\x61lculation\x12\x33\n\tCalculate\x12\x12.sample.C2SRequest\x1a\x10.sample.S2CReply\"\x00\x62\x06proto3'
)



_C2SREQUEST_OPERATION = _descriptor.EnumDescriptor(
  name='Operation',
  full_name='sample.C2SRequest.Operation',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Add', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='Subtract', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='Multiply', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='Divide', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=118,
  serialized_end=178,
)
_sym_db.RegisterEnumDescriptor(_C2SREQUEST_OPERATION)


_C2SREQUEST = _descriptor.Descriptor(
  name='C2SRequest',
  full_name='sample.C2SRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='lhs', full_name='sample.C2SRequest.lhs', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='rhs', full_name='sample.C2SRequest.rhs', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='op', full_name='sample.C2SRequest.op', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _C2SREQUEST_OPERATION,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=178,
)


_S2CREPLY = _descriptor.Descriptor(
  name='S2CReply',
  full_name='sample.S2CReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='sample.S2CReply.result', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='message', full_name='sample.S2CReply.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=180,
  serialized_end=223,
)

_C2SREQUEST.fields_by_name['op'].enum_type = _C2SREQUEST_OPERATION
_C2SREQUEST_OPERATION.containing_type = _C2SREQUEST
DESCRIPTOR.message_types_by_name['C2SRequest'] = _C2SREQUEST
DESCRIPTOR.message_types_by_name['S2CReply'] = _S2CREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

C2SRequest = _reflection.GeneratedProtocolMessageType('C2SRequest', (_message.Message,), {
  'DESCRIPTOR' : _C2SREQUEST,
  '__module__' : 'protos.calculator_pb2'
  # @@protoc_insertion_point(class_scope:sample.C2SRequest)
  })
_sym_db.RegisterMessage(C2SRequest)

S2CReply = _reflection.GeneratedProtocolMessageType('S2CReply', (_message.Message,), {
  'DESCRIPTOR' : _S2CREPLY,
  '__module__' : 'protos.calculator_pb2'
  # @@protoc_insertion_point(class_scope:sample.S2CReply)
  })
_sym_db.RegisterMessage(S2CReply)



_CALCULATION = _descriptor.ServiceDescriptor(
  name='Calculation',
  full_name='sample.Calculation',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=225,
  serialized_end=291,
  methods=[
  _descriptor.MethodDescriptor(
    name='Calculate',
    full_name='sample.Calculation.Calculate',
    index=0,
    containing_service=None,
    input_type=_C2SREQUEST,
    output_type=_S2CREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_CALCULATION)

DESCRIPTOR.services_by_name['Calculation'] = _CALCULATION

# @@protoc_insertion_point(module_scope)
