# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/figurerecognition.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='protos/figurerecognition.proto',
  package='sample',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1eprotos/figurerecognition.proto\x12\x06sample\"#\n\x12RecognitionRequest\x12\r\n\x05image\x18\x01 \x01(\t\"%\n\x13RecognitionResponse\x12\x0e\n\x06number\x18\x01 \x01(\x05\x32[\n\x11\x46igureRecognition\x12\x46\n\tRecognize\x12\x1a.sample.RecognitionRequest\x1a\x1b.sample.RecognitionResponse\"\x00\x62\x06proto3'
)




_RECOGNITIONREQUEST = _descriptor.Descriptor(
  name='RecognitionRequest',
  full_name='sample.RecognitionRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='image', full_name='sample.RecognitionRequest.image', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=42,
  serialized_end=77,
)


_RECOGNITIONRESPONSE = _descriptor.Descriptor(
  name='RecognitionResponse',
  full_name='sample.RecognitionResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='number', full_name='sample.RecognitionResponse.number', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=79,
  serialized_end=116,
)

DESCRIPTOR.message_types_by_name['RecognitionRequest'] = _RECOGNITIONREQUEST
DESCRIPTOR.message_types_by_name['RecognitionResponse'] = _RECOGNITIONRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RecognitionRequest = _reflection.GeneratedProtocolMessageType('RecognitionRequest', (_message.Message,), {
  'DESCRIPTOR' : _RECOGNITIONREQUEST,
  '__module__' : 'protos.figurerecognition_pb2'
  # @@protoc_insertion_point(class_scope:sample.RecognitionRequest)
  })
_sym_db.RegisterMessage(RecognitionRequest)

RecognitionResponse = _reflection.GeneratedProtocolMessageType('RecognitionResponse', (_message.Message,), {
  'DESCRIPTOR' : _RECOGNITIONRESPONSE,
  '__module__' : 'protos.figurerecognition_pb2'
  # @@protoc_insertion_point(class_scope:sample.RecognitionResponse)
  })
_sym_db.RegisterMessage(RecognitionResponse)



_FIGURERECOGNITION = _descriptor.ServiceDescriptor(
  name='FigureRecognition',
  full_name='sample.FigureRecognition',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=118,
  serialized_end=209,
  methods=[
  _descriptor.MethodDescriptor(
    name='Recognize',
    full_name='sample.FigureRecognition.Recognize',
    index=0,
    containing_service=None,
    input_type=_RECOGNITIONREQUEST,
    output_type=_RECOGNITIONRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_FIGURERECOGNITION)

DESCRIPTOR.services_by_name['FigureRecognition'] = _FIGURERECOGNITION

# @@protoc_insertion_point(module_scope)
