# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from protos import multiplayer_pb2 as protos_dot_multiplayer__pb2


class MultiplayerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Join = channel.unary_unary(
                '/sample.Multiplayer/Join',
                request_serializer=protos_dot_multiplayer__pb2.JoinRequest.SerializeToString,
                response_deserializer=protos_dot_multiplayer__pb2.JoinResponse.FromString,
                )
        self.Move = channel.unary_unary(
                '/sample.Multiplayer/Move',
                request_serializer=protos_dot_multiplayer__pb2.MoveRequest.SerializeToString,
                response_deserializer=protos_dot_multiplayer__pb2.MoveResponse.FromString,
                )
        self.SyncPos = channel.stream_stream(
                '/sample.Multiplayer/SyncPos',
                request_serializer=protos_dot_multiplayer__pb2.RegisterSyncPos.SerializeToString,
                response_deserializer=protos_dot_multiplayer__pb2.PushSyncPos.FromString,
                )


class MultiplayerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Join(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Move(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SyncPos(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MultiplayerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Join': grpc.unary_unary_rpc_method_handler(
                    servicer.Join,
                    request_deserializer=protos_dot_multiplayer__pb2.JoinRequest.FromString,
                    response_serializer=protos_dot_multiplayer__pb2.JoinResponse.SerializeToString,
            ),
            'Move': grpc.unary_unary_rpc_method_handler(
                    servicer.Move,
                    request_deserializer=protos_dot_multiplayer__pb2.MoveRequest.FromString,
                    response_serializer=protos_dot_multiplayer__pb2.MoveResponse.SerializeToString,
            ),
            'SyncPos': grpc.stream_stream_rpc_method_handler(
                    servicer.SyncPos,
                    request_deserializer=protos_dot_multiplayer__pb2.RegisterSyncPos.FromString,
                    response_serializer=protos_dot_multiplayer__pb2.PushSyncPos.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sample.Multiplayer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Multiplayer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Join(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sample.Multiplayer/Join',
            protos_dot_multiplayer__pb2.JoinRequest.SerializeToString,
            protos_dot_multiplayer__pb2.JoinResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Move(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sample.Multiplayer/Move',
            protos_dot_multiplayer__pb2.MoveRequest.SerializeToString,
            protos_dot_multiplayer__pb2.MoveResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SyncPos(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/sample.Multiplayer/SyncPos',
            protos_dot_multiplayer__pb2.RegisterSyncPos.SerializeToString,
            protos_dot_multiplayer__pb2.PushSyncPos.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
