# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/multiplayer.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='protos/multiplayer.proto',
  package='sample',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x18protos/multiplayer.proto\x12\x06sample\" \n\x08Position\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\",\n\x0bJoinRequest\x12\x1d\n\x03pos\x18\x01 \x01(\x0b\x32\x10.sample.Position\":\n\x0cJoinResponse\x12\x0b\n\x03uid\x18\x01 \x01(\x05\x12\x1d\n\x03pos\x18\x02 \x01(\x0b\x32\x10.sample.Position\",\n\x0bMoveRequest\x12\x1d\n\x03pos\x18\x01 \x01(\x0b\x32\x10.sample.Position\"-\n\x0cMoveResponse\x12\x1d\n\x03pos\x18\x01 \x01(\x0b\x32\x10.sample.Position\"\x11\n\x0fRegisterSyncPos\"9\n\x0bPushSyncPos\x12\x0b\n\x03uid\x18\x01 \x01(\x05\x12\x1d\n\x03pos\x18\x02 \x01(\x0b\x32\x10.sample.Position2\xb6\x01\n\x0bMultiplayer\x12\x33\n\x04Join\x12\x13.sample.JoinRequest\x1a\x14.sample.JoinResponse\"\x00\x12\x33\n\x04Move\x12\x13.sample.MoveRequest\x1a\x14.sample.MoveResponse\"\x00\x12=\n\x07SyncPos\x12\x17.sample.RegisterSyncPos\x1a\x13.sample.PushSyncPos\"\x00(\x01\x30\x01\x62\x06proto3'
)




_POSITION = _descriptor.Descriptor(
  name='Position',
  full_name='sample.Position',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='sample.Position.x', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='y', full_name='sample.Position.y', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=68,
)


_JOINREQUEST = _descriptor.Descriptor(
  name='JoinRequest',
  full_name='sample.JoinRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='pos', full_name='sample.JoinRequest.pos', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=70,
  serialized_end=114,
)


_JOINRESPONSE = _descriptor.Descriptor(
  name='JoinResponse',
  full_name='sample.JoinResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='uid', full_name='sample.JoinResponse.uid', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pos', full_name='sample.JoinResponse.pos', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=116,
  serialized_end=174,
)


_MOVEREQUEST = _descriptor.Descriptor(
  name='MoveRequest',
  full_name='sample.MoveRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='pos', full_name='sample.MoveRequest.pos', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=176,
  serialized_end=220,
)


_MOVERESPONSE = _descriptor.Descriptor(
  name='MoveResponse',
  full_name='sample.MoveResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='pos', full_name='sample.MoveResponse.pos', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=222,
  serialized_end=267,
)


_REGISTERSYNCPOS = _descriptor.Descriptor(
  name='RegisterSyncPos',
  full_name='sample.RegisterSyncPos',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=269,
  serialized_end=286,
)


_PUSHSYNCPOS = _descriptor.Descriptor(
  name='PushSyncPos',
  full_name='sample.PushSyncPos',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='uid', full_name='sample.PushSyncPos.uid', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pos', full_name='sample.PushSyncPos.pos', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=288,
  serialized_end=345,
)

_JOINREQUEST.fields_by_name['pos'].message_type = _POSITION
_JOINRESPONSE.fields_by_name['pos'].message_type = _POSITION
_MOVEREQUEST.fields_by_name['pos'].message_type = _POSITION
_MOVERESPONSE.fields_by_name['pos'].message_type = _POSITION
_PUSHSYNCPOS.fields_by_name['pos'].message_type = _POSITION
DESCRIPTOR.message_types_by_name['Position'] = _POSITION
DESCRIPTOR.message_types_by_name['JoinRequest'] = _JOINREQUEST
DESCRIPTOR.message_types_by_name['JoinResponse'] = _JOINRESPONSE
DESCRIPTOR.message_types_by_name['MoveRequest'] = _MOVEREQUEST
DESCRIPTOR.message_types_by_name['MoveResponse'] = _MOVERESPONSE
DESCRIPTOR.message_types_by_name['RegisterSyncPos'] = _REGISTERSYNCPOS
DESCRIPTOR.message_types_by_name['PushSyncPos'] = _PUSHSYNCPOS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Position = _reflection.GeneratedProtocolMessageType('Position', (_message.Message,), {
  'DESCRIPTOR' : _POSITION,
  '__module__' : 'protos.multiplayer_pb2'
  # @@protoc_insertion_point(class_scope:sample.Position)
  })
_sym_db.RegisterMessage(Position)

JoinRequest = _reflection.GeneratedProtocolMessageType('JoinRequest', (_message.Message,), {
  'DESCRIPTOR' : _JOINREQUEST,
  '__module__' : 'protos.multiplayer_pb2'
  # @@protoc_insertion_point(class_scope:sample.JoinRequest)
  })
_sym_db.RegisterMessage(JoinRequest)

JoinResponse = _reflection.GeneratedProtocolMessageType('JoinResponse', (_message.Message,), {
  'DESCRIPTOR' : _JOINRESPONSE,
  '__module__' : 'protos.multiplayer_pb2'
  # @@protoc_insertion_point(class_scope:sample.JoinResponse)
  })
_sym_db.RegisterMessage(JoinResponse)

MoveRequest = _reflection.GeneratedProtocolMessageType('MoveRequest', (_message.Message,), {
  'DESCRIPTOR' : _MOVEREQUEST,
  '__module__' : 'protos.multiplayer_pb2'
  # @@protoc_insertion_point(class_scope:sample.MoveRequest)
  })
_sym_db.RegisterMessage(MoveRequest)

MoveResponse = _reflection.GeneratedProtocolMessageType('MoveResponse', (_message.Message,), {
  'DESCRIPTOR' : _MOVERESPONSE,
  '__module__' : 'protos.multiplayer_pb2'
  # @@protoc_insertion_point(class_scope:sample.MoveResponse)
  })
_sym_db.RegisterMessage(MoveResponse)

RegisterSyncPos = _reflection.GeneratedProtocolMessageType('RegisterSyncPos', (_message.Message,), {
  'DESCRIPTOR' : _REGISTERSYNCPOS,
  '__module__' : 'protos.multiplayer_pb2'
  # @@protoc_insertion_point(class_scope:sample.RegisterSyncPos)
  })
_sym_db.RegisterMessage(RegisterSyncPos)

PushSyncPos = _reflection.GeneratedProtocolMessageType('PushSyncPos', (_message.Message,), {
  'DESCRIPTOR' : _PUSHSYNCPOS,
  '__module__' : 'protos.multiplayer_pb2'
  # @@protoc_insertion_point(class_scope:sample.PushSyncPos)
  })
_sym_db.RegisterMessage(PushSyncPos)



_MULTIPLAYER = _descriptor.ServiceDescriptor(
  name='Multiplayer',
  full_name='sample.Multiplayer',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=348,
  serialized_end=530,
  methods=[
  _descriptor.MethodDescriptor(
    name='Join',
    full_name='sample.Multiplayer.Join',
    index=0,
    containing_service=None,
    input_type=_JOINREQUEST,
    output_type=_JOINRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Move',
    full_name='sample.Multiplayer.Move',
    index=1,
    containing_service=None,
    input_type=_MOVEREQUEST,
    output_type=_MOVERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='SyncPos',
    full_name='sample.Multiplayer.SyncPos',
    index=2,
    containing_service=None,
    input_type=_REGISTERSYNCPOS,
    output_type=_PUSHSYNCPOS,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_MULTIPLAYER)

DESCRIPTOR.services_by_name['Multiplayer'] = _MULTIPLAYER

# @@protoc_insertion_point(module_scope)
